/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package libzinc

class Pand(var height: Double, var length: Double) {
    var perimeter = (height + length) * 2
}

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
